name: Primer workflow

on: push
jobs:
    validar:
     runs-on: ubuntu-latest
     steps:
          - name: Bajar codigo
            uses: actions/checkout@v5
          - name: Ejecutar codigo pip
            run: pip installl pytest
          - name: Ejecutar codigo test
            run: pytest test.py
